import Head from 'next/head';

import { gql, useQuery, useMutation } from '@apollo/client';
import { GET_ALL_LINKS } from '../graphql/Queries';

import Header from '../components/Header';
import PostsList from '../components/PostsList';

import styles from '../styles/Home.module.scss';

export default function Home() {
    const { data, loading, error } = useQuery(GET_ALL_LINKS);

    if (loading) return <p>Loading...</p>;
    if (error) return <p>Oh no... {error.message}</p>;
    const links = data.feed.links;
    return (
        <>
            <Head>
                <title>Reddit clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <PostsList links={links} />
            </main>
        </>
    );
}
